version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # We update the EF Core dependency manually
      - dependency-name: "Microsoft.EntityFrameworkCore.*"
      - dependency-name: "Microsoft.Extensions.*"
    labels:
      - dependabot

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependabot
